"""Set default UUID for id column

Revision ID: 10712631442b
Revises: 8d5e34d77af3
Create Date: 2025-01-10 17:27:32.867519

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '10712631442b'
down_revision = '8d5e34d77af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mediadetails', 'content_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mediadetails', 'content_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###