"""Rename thematic_locations to top_locations in ContentEvaluation

Revision ID: 400604920812
Revises: b4e714c5f297
Create Date: 2025-03-13 23:06:06.199724

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '400604920812'
down_revision = 'b4e714c5f297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###