"""Adding top locations and entities to content

Revision ID: 8d5e34d77af3
Revises: ef87360117c8
Create Date: 2025-01-10 17:20:27.850103

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = '8d5e34d77af3'
down_revision = 'ef87360117c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###