"""Rename thematic_locations to top_locations in ContentEvaluation

Revision ID: b4e714c5f297
Revises: 6026e20364f8
Create Date: 2025-03-13 11:52:28.356650

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4e714c5f297'
down_revision = '6026e20364f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contentevaluation', sa.Column('top_locations', sa.ARRAY(sa.Text()), nullable=True))
    op.drop_column('contentevaluation', 'thematic_locations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contentevaluation', sa.Column('thematic_locations', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.drop_column('contentevaluation', 'top_locations')
    # ### end Alembic commands ###