"""Initial migration

Revision ID: bbcc17e0f99d
Revises: ab8bdd0db41d
Create Date: 2025-04-01 07:08:55.200699

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector  
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision = 'bbcc17e0f99d'
down_revision = 'ab8bdd0db41d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###